FROM python:3-slim

{% if apt_install is defined and apt_install %}
RUN apt update && apt install -y {{ apt_install|join(" ") }}
{% endif %}

WORKDIR /app

{% if (requirements is defined) and requirements %}
RUN pip install {{ requirements|join(" ") }}
{% endif %}

COPY {{ script_name }} app.py

CMD ["python"]