{% if conda %}
FROM mambaorg/micromamba
{% else %}
FROM python:3-slim
{% endif %}

{% if apt_install is defined and apt_install %}
RUN apt update && apt install -y {{ apt_install|join(" ") }}
{% endif %}

WORKDIR /app

{% if conda %}
RUN micromamba install -y -n base -c conda-forge python={{ python_version|default("3.12", true) }} {{ conda|join(" ") }}
ARG MAMBA_DOCKERFILE_ACTIVATE=1
{% endif %}

{% if (requirements is defined) and requirements %}
RUN pip install {{ requirements|join(" ") }}
{% endif %}

COPY {{ script_name }} app.py

CMD ["python"]